Repository DEPthes/MJU-Council-Web, pull requests merged in 2024-11, with the labels that each got.

#6 Feat/#1 활동보고페이지UI
  src/Router.tsx
  src/assets/common/Arrow.svg
  src/assets/common/Attachment.svg
  src/assets/common/PageDoubleIcon.svg
  src/assets/common/PageIcon.svg
  src/assets/common/Search.svg
  src/assets/common/index.ts
  src/components/ActivityReport/ActivityReportHeader.tsx
  src/components/ActivityReport/BusinessDetail/BusinessDetailComponent.tsx
  src/components/ActivityReport/BusinessLlist/BusinessListComponent.tsx
  src/components/ActivityReport/BusinessLlist/BusinessListItem.tsx
  src/components/ActivityReport/Coalition/CoalitionItem.tsx
  src/components/ActivityReport/CoalitionDetail/CoalitionDetailComponent.tsx
  src/components/ActivityReport/PolicyList/PolicyListComponent.tsx
  src/components/ActivityReport/PolicyList/PolicyListPromiseComponent.tsx
  src/components/ActivityReport/PolicyList/PolicyListTab.tsx
  src/components/common/FileButton.tsx
  src/components/common/GoListButton.tsx
  src/components/common/PageComponent.tsx
  src/components/common/SearchComponent.tsx
  src/constants/ActivityReport/PolicyList/index.ts
  src/pages/ActivityReport/BusinessListDetailPage.tsx
  src/pages/ActivityReport/BusinessListPage.tsx
  src/pages/ActivityReport/BusinessSearchResultPage.tsx
  src/pages/ActivityReport/CoalitionDetailPage.tsx
  src/pages/ActivityReport/CoalitionPage.tsx
  src/pages/ActivityReport/PolicyList.tsx
  src/pages/ActivityReport/PolicyListPage.tsx
  src/styles/ActivityReport/ActivityReportHeaderStyle.ts
  src/styles/ActivityReport/BusinessDetail/BusinessDetailComponentStyle.ts
  src/styles/ActivityReport/BusinessDetail/BusinessListDetailPageStyle.ts
  src/styles/ActivityReport/BusinessList/BusinessListComponentStyle.ts
  src/styles/ActivityReport/BusinessList/BusinessListItemStyle.ts
  src/styles/ActivityReport/BusinessList/BusinessListPageComponentStyle.ts
  src/styles/ActivityReport/BusinessList/BusinessListPageStyle.ts
  src/styles/ActivityReport/BusinessSearchResult/BusinessSearchResultStyle.ts
  src/styles/ActivityReport/Coalition/CoalitionItemStyle.ts
  src/styles/ActivityReport/Coalition/CoalitionPageStyle.ts
  src/styles/ActivityReport/CoalitionDetail/CoalitionDetailComponentStyle.ts
  src/styles/ActivityReport/CoalitionDetail/CoalitionDetailPageStyle.ts
  src/styles/ActivityReport/PolicyList/PolicyListComponentStyle.ts
  src/styles/ActivityReport/PolicyList/PolicyListPageStyle.ts
  src/styles/ActivityReport/PolicyList/PolicyListPromiseComponentStyle.ts
  src/styles/ActivityReport/PolicyList/PolicyListTabStyle.ts
  src/styles/common/FileButtonStyle.ts
  src/styles/common/GoListButtonStyle.ts
  src/styles/common/SearchComponentStyle.ts
  src/types/ActivityReport/Coalition/index.ts
  src/types/ActivityReport/PolicyList/index.ts
  src/utils/ActivitiyReport/index.ts
Labels: enhancement

#10 [fix] width, height 하드 코딩 수정
  src/assets/image/Line 24.png
  src/assets/image/Line 24.svg
  src/assets/image/Rectangle 34625295.png
  src/assets/image/Rectangle 34625295.svg
  src/assets/image/Rectangle 34625296.png
  src/assets/image/Rectangle 34625296.svg
  src/components/Home/Banner.tsx
  src/components/Home/Footer.tsx
  src/components/Home/HomeCategory.tsx
  src/components/Home/HomeNotice.tsx
  src/components/Home/NavBar.tsx
  src/pages/MainPage/Home.tsx
  src/pages/SideMenuPage/SideMenu.tsx
  src/styles/Home/Component/BannerComponentStyle.ts
  src/styles/Home/Component/FooterComponentStyle.ts
  src/styles/Home/Component/HomeCategoryComponentStyle.ts
  src/styles/Home/Component/HomeNoticeComponentStyle.ts
  src/styles/Home/Component/NavBarComponentStyle.ts
  src/styles/Home/Page/HomePageStyle.ts
Labels: enhancement

#15 [feat/#13] Layout 컴퍼넌트 생성
  src/Router.tsx
  src/components/Home/Footer.tsx
  src/components/Home/NavBar.tsx
  src/components/Layout.tsx
  src/pages/MainPage/Home.tsx
  src/styles/ActivityReport/BusinessSearchResult/BusinessSearchResultStyle.ts
  src/styles/Home/Component/FooterComponentStyle.ts
  src/styles/Home/Component/NavBarComponentStyle.ts
  src/styles/Layout.ts
  src/styles/common/GoListButtonStyle.ts
  src/styles/common/SearchComponentStyle.ts
Labels: enhancement

#14 [fix] #2메인페이지 하드코딩 수정 및 버튼 색 수정
  src/assets/image/Line 24.png
  src/components/Home/Banner.tsx
  src/components/Home/HomeNotice.tsx
  src/styles/Home/Component/BannerComponentStyle.ts
  src/styles/Home/Component/FooterComponentStyle.ts
  src/styles/Home/Component/HomeNoticeComponentStyle.ts
  src/styles/Home/Component/NavBarComponentStyle.ts
  src/styles/Home/Page/HomePageStyle.ts
Labels: enhancement

#19 [feat/#11] 공지사항 UI 제작
  src/Router.tsx
  src/assets/image/EventArrow.svg
  src/components/News/DetailContent.tsx
  src/components/News/EventListCard.tsx
  src/components/News/EventListDetail.tsx
  src/components/News/EventListGuideCard.tsx
  src/components/News/NoticeListItem.tsx
  src/components/common/DetailHeader.tsx
  src/components/common/PageComponent.tsx
  src/pages/ActivityReport/BusinessListPage.tsx
  src/pages/ActivityReport/BusinessSearchResultPage.tsx
  src/pages/ActivityReport/CoalitionPage.tsx
  src/pages/News/EventListDetailPage.tsx
  src/pages/News/EventListGuideDetailPage.tsx
  src/pages/News/EventListPage.tsx
  src/pages/News/NoticeListDetailPage.tsx
  src/pages/News/NoticeListPage.tsx
  src/styles/ActivityReport/BusinessList/BusinessListPageComponentStyle.ts
  src/styles/News/DetailContentStyle.ts
  src/styles/News/EventListCardStyle.ts
  src/styles/News/EventListDetailPageStyle.ts
  src/styles/News/EventListDetailStyle.ts
  src/styles/News/EventListGuideCardStyle.ts
  src/styles/News/NoticeListItemStyle.ts
  src/styles/News/NoticeListPageStyle.ts
  src/styles/common/DetailHeaderStyle.ts
  src/styles/common/FileButtonStyle.ts
  src/styles/common/GoListButtonStyle.ts
  src/types/News/event.ts
  src/types/News/notice.ts
  src/types/common.ts
  tsconfig.app.json
Labels: ✨ Feature, 🎨 Html&css

#21 Feat/#18 indicator
  src/Router.tsx
  src/assets/common/Home.svg
  src/assets/common/Interface.svg
  src/assets/common/TextBanner.svg
  src/assets/common/index.ts
  src/components/Layout.tsx
  src/components/common/Indicator.tsx
  src/components/common/TextBanner.tsx
  src/constants/pathToKoreanMap.ts
  src/styles/Layout.ts
  src/styles/common/IndicatorStyle.ts
  src/utils/parseUrlToArray.ts
Labels: ✨ Feature, 🎨 Html&css

#24 [fix/#2] 메인페이지navbar고정
  src/components/Home/NavBar.tsx
  src/styles/Home/Component/BannerComponentStyle.ts
  src/styles/Home/Component/NavBarComponentStyle.ts
  src/styles/Home/Page/HomePageStyle.ts
Labels: 🎨 Html&css

#25 [Feat/#3] 홈메뉴UI
  src/assets/image/ArrowDown.svg
  src/assets/image/ArrowUp.svg
  src/components/Home/NavBar.tsx
  src/components/SideBar.tsx
  src/components/SideMenu/BigSideMenu.tsx
  src/components/SideMenu/SmallSideMenu.tsx
  src/pages/SideMenuPage/SideMenu.tsx
  src/styles/Layout.ts
  src/styles/SideMenu/SideMenuComponentStyle.ts
Labels: ✨ Feature, 🎨 Html&css

#29 fix: TypeScript build error 해결
  src/components/Introduction/Organization/Organization.tsx
  src/pages/Introduction/IntroductionPage.tsx
Labels: 🐞 BugFix

#31 [fix/#30] 메인페이지 버그 수정
  src/Router.tsx
  src/assets/banner_dummy.json
  src/assets/image/Banner1.png
  src/assets/image/Banner1.svg
  src/assets/image/Banner2.png
  src/assets/image/Banner2.svg
  src/assets/image/Banner3.png
  src/assets/image/Banner3.svg
  src/assets/image/Banner4.png
  src/assets/image/Banner4.svg
  src/assets/image/Rectangle 34625295.png
  src/assets/image/Rectangle 34625296.png
  src/components/Home/Banner.tsx
  src/components/Home/Footer.tsx
  src/components/Home/HomeCategory.tsx
  src/components/Home/HomeNotice.tsx
  src/components/Home/HomePageBtn.tsx
  src/components/Introduction/CentralCommitee/StudentOrganization.tsx
  src/components/Introduction/IntroTextBanner.tsx
  src/pages/Introduction/IntroductionPage.tsx
  src/pages/SideMenuPage/SideMenu.tsx
  src/styles/Home/Component/BannerComponentStyle.ts
  src/styles/Home/Component/FooterComponentStyle.ts
  src/styles/Home/Component/HomeBtnComponentStyle.ts
  src/styles/Home/Component/HomeCategoryComponentStyle.ts
  src/styles/Home/Component/HomeNoticeComponentStyle.ts
Labels: 🎨 Html&css, 🐞 BugFix

#33 Fix/#32 배너 목록 추가
  src/components/Home/HomeCategory.tsx
  src/constants/pathToKoreanMap.ts
Labels: ✨ Feature, 🐞 BugFix

#35 fix: 가로 비율 수정
  src/styles/ActivityReport/Coalition/CoalitionPageStyle.ts
Labels: 🐞 BugFix

#36 fix: 페이지 아이콘 간격 수정
  src/styles/ActivityReport/BusinessList/BusinessListPageComponentStyle.ts
Labels: 🐞 BugFix
